FROM raffauser/leonardoplanner:devel

RUN cd /usr/local/src/ && curl -L http://github.com/rsecchi/eurotherm/archive/frame.tar.gz | tar zxf - && mv eurotherm-frame eurotherm
COPY config.sh  /root/config.sh
ENTRYPOINT ["/bin/bash","/root/config.sh"]


