FROM httpd:latest

COPY httpd.conf /usr/local/apache2/conf/httpd.conf

### Add the a dynamic link to banner.png

RUN apt-get update && apt-get -y install python3-full python3-ezdxf python3-openpyxl python3-docx python3-numpy



